In [36]:
import pickle
import os
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA



os.chdir('./')              	# location where files are stored (main + utility)
save_loc = './results'    			# location to save results
# save_loc = './results_car_hacking_model'    		# location to save results for carhacking
results_AE_SHAP, history_AE_SHAP = pickle.load(open("{}/data_1.pkl".format(save_loc), "rb"))
results_model = pickle.load(open("{}/results.pkl".format(save_loc), "rb"))
model = pickle.load(open("{}/XGBoost.pkl".format(save_loc), "rb"))

In [37]:

# Exibe todas as métricas disponíveis
for key, value in results_model.items():
    print(f"{key}:")
    print(value)
    print("-" * 40)

# Exemplo: acessar métricas específicas
print("Acurácia no treino:", results_model['performance_model_train']['ACCURACY'].values[0])
print("Acurácia no teste:", results_model['performance_model_test']['ACCURACY'].values[0])
print("TPR novos ataques:", results_model.get('TPR_new_attacks', 'N/A'))
print("TPR novos ataques overall:", results_model.get('TPR_new_attacks_overall', 'N/A'))

y_pred_train:
[0 0 1 ... 0 1 0]
----------------------------------------
y_pred_test:
[1 1 0 ... 1 0 1]
----------------------------------------
y_pred_test_21:
[0 0 1 ... 0 1 0]
----------------------------------------
performance_model_train:
        TN   FP   FN       TP  ACCURACY    RECALL  PRECISION        F1  \
0  67337.0  6.0  5.0  58625.0  0.999913  0.999915   0.999898  0.999906   

        FPR       TNR       FNR   T-SCORE  
0  0.000089  0.999911  0.000085  0.999812  
----------------------------------------
performance_model_test:
       TN     FP      FN      TP  ACCURACY    RECALL  PRECISION        F1  \
0  9434.0  277.0  4413.0  8420.0  0.791962  0.656121    0.96815  0.782164   

        FPR       TNR       FNR   T-SCORE  
0  0.028524  0.971476  0.343879  0.642258  
----------------------------------------
performance_model_test_21:
       TN     FP      FN      TP  ACCURACY    RECALL  PRECISION        F1  \
0  1880.0  272.0  4413.0  5285.0  0.604641  0.544958   0.951053  

In [38]:
# Exibe todas as métricas e arrays principais do results_AE_SHAP
for key, value in results_AE_SHAP.items():
    print(f"{key}:")
    # Para arrays grandes, mostra apenas o tipo e shape
    if hasattr(value, 'shape'):
        print(f"Array shape: {value.shape}")
    elif isinstance(value, dict):
        print(f"Dict com chaves: {list(value.keys())}")
    else:
        print(value)
    print("-" * 40)

# Exemplo: acessar métricas específicas se existirem
if 'performance_new_attacks' in results_AE_SHAP:
    print("Performance AE (novos ataques):")
    print(results_AE_SHAP['performance_new_attacks'])
if 'performance_overall' in results_AE_SHAP:
    print("Performance AE (overall):")
    print(results_AE_SHAP['performance_overall'])



# results_AE_SHAP['all_attack_pred_locs'] = np.unique(np.concatenate((results_AE_SHAP['new_attack_pred_locs'], np.where(results_model['y_pred_test']==1)[0] )))
# results_AE_SHAP['y_pred_all'] = np.zeros(len(data_kdd['Y_test_bin']),)
# results_AE_SHAP['y_pred_all'][results_AE_SHAP['all_attack_pred_locs']] = 1
# results_AE_SHAP['performance_overall'] = utf.compute_performance_stats(data_kdd['Y_test_bin'], results_AE_SHAP['y_pred_all'])

shap_train:
Array shape: (125973, 41)
----------------------------------------
shap_test:
Array shape: (22544, 41)
----------------------------------------
scaler:
MinMaxScaler(feature_range=(-1, 1))
----------------------------------------
shap_train_scaled:
Array shape: (125973, 41)
----------------------------------------
shap_test_scaled:
Array shape: (22544, 41)
----------------------------------------
x_data:
Array shape: (53874, 41)
----------------------------------------
val_data:
Array shape: (13469, 41)
----------------------------------------
parameters:
Dict com chaves: ['dense_1_units', 'dense_1_activation', 'dense_2_units', 'dense_2_activation', 'dense_3_units', 'dense_3_activation', 'dense_4_units', 'dense_4_activation', 'dense_5_units', 'dense_5_activation', 'dense_6_units', 'dense_6_activation']
----------------------------------------
grid_search:
[[0.050053346902132034, 0.03886282444000244, [512, 128, 8, 128, 512, 41], ['relu', 'relu', 'relu', 'relu', 'relu', 'tanh'

In [39]:

# Performance AE (novos ataques):
#         TN      FP      FN     TP  ACCURACY    RECALL  PRECISION       F1  \
# 0  16332.0  2462.0  3146.0  604.0  0.751242  0.161067   0.196999  0.17723   

#         FPR       TNR       FNR   T-SCORE  
# 0  0.130999  0.869001  0.838933  0.097231  
# Performance AE (overall):
#        TN     FP      FN      TP  ACCURACY    RECALL  PRECISION        F1  \
# 0  9434.0  277.0  4413.0  8420.0  0.791962  0.656121    0.96815  0.782164   



# =====================================================

# Performance AE (novos ataques):
#         TN      FP      FN     TP  ACCURACY    RECALL  PRECISION        F1  \
# 0  15079.0  3715.0  3025.0  725.0  0.701029  0.193333   0.163288  0.177045   

#         FPR       TNR       FNR  T-SCORE  
# 0  0.197669  0.802331  0.806667  0.09712  
# Performance AE (overall):
#        TN     FP      FN      TP  ACCURACY    RECALL  PRECISION        F1  \
# 0  9434.0  277.0  4413.0  8420.0  0.791962  0.656121    0.96815  0.782164   

#         FPR       TNR       FNR   T-SCORE  
# 0  0.028524  0.971476  0.343879  0.642258  




# Performance AE (novos ataques):
#         TN     FP      FN     TP  ACCURACY    RECALL  PRECISION        F1  \
# 0  18103.0  691.0  2938.0  812.0  0.839026  0.216533   0.540253  0.309157   

#         FPR       TNR       FNR   T-SCORE  
# 0  0.036767  0.963233  0.783467  0.182842  
# Performance AE (overall):
#        TN     FP      FN      TP  ACCURACY    RECALL  PRECISION        F1  \
# 0  9434.0  277.0  4405.0  8428.0  0.792317  0.656744   0.968179  0.782617   

#         FPR       TNR       FNR   T-SCORE  
# 0  0.028524  0.971476  0.343256  0.642868  